
namespace pax.BlazorChartJs;

public record ChartJsAxisTick
{
    public string? BackdropColor { get; set; }
    public Padding? BackdropPadding { get; set; }
    public bool? Display { get; set; }
    public string? Color { get; set; }
    public Font? Font { get; set; }
    /// <summary>
    /// it defines options for the major tick marks that are generated by the axis. <see href="https://www.chartjs.org/docs/latest/axes/styling.html#major-tick-configuration">ChartJs</see>
    /// </summary>      
    public object? Major { get; set; }
    public int? Padding { get; set; }
    public bool? ShowLabelBackdrop { get; set; }
    public object? TextStrokeColor { get; set; }
    public int? TextStrokeWidth { get; set; }
    /// <summary>
    /// z-index of tick layer. Useful when ticks are drawn on chart area. Values &lt;= 0 are drawn under datasets, &gt; 0 on top.
    /// </summary>   
    public int? Z { get; set; }
}