name: Playwright Tests
on:
  workflow_run:
    workflows: ["Deploy Blazor WASM to GitHub Pages"]
    types:
      - completed
jobs:
    test:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '10.0.x'
        - run: dotnet build ./tests/pax.BlazorChartJs.pwtests/pax.BlazorChartJs.pwtests.csproj
        - name: Ensure browsers are installed
          run: pwsh ./tests/pax.BlazorChartJs.pwtests/bin/Debug/net10.0/playwright.ps1 install --with-deps
        - name: Run your tests
          run: dotnet test ./tests/pax.BlazorChartJs.pwtests
